cask_args appdir: '/Applications'

brew 'jenv'
brew 'nodenv'
brew 'pyenv'
brew 'rbenv'

cask '1password'
cask 'android-studio'
cask 'google-drive'
cask 'rar'
cask 'raycast'
cask 'rectangle'
cask 'visual-studio-code'
cask 'vlc'
