cask_args appdir: '/Applications'

tap 'caskroom/cask'

brew 'git-lfs'
brew 'heroku'
brew 'mongodb'
brew 'mono'
brew 'node'
brew 'postgres'

cask 'java'

cask 'adobe-creative-cloud'
cask 'android-sdk'
cask 'dashlane'
cask 'dropbox'
cask 'figma'
cask 'firefox'
cask 'google-backup-and-sync'
cask 'google-chrome'
cask 'iterm2'
cask 'paw'
cask 'pgadmin4'
cask 'sketch'
cask 'slack'
cask 'visual-studio-code'
cask 'vlc'
cask 'zeplin'
